name: Daily US Market Scanner

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install yfinance pandas numpy ta

      - name: Run scanner
        run: |
          echo "COMMIT CHECK"
          git rev-parse HEAD
          python scanner.py

      - name: Save CSV to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add history.csv
          git commit -m "update history" || echo "no changes"
          git push
